Repository boostcamp-2020/IssueTracker-17, pull requests merged in 2020-11, with the labels that each got.

#67 Feature/iOS/codeAble 모든 객체에 Codable 적용
  IOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IOS/IssueTracker/IssueTracker/Controller/LabelDetailViewController.swift
  IOS/IssueTracker/IssueTracker/Controller/LabelViewController.swift
  IOS/IssueTracker/IssueTracker/Controller/MilestoneDetailViewController.swift
  IOS/IssueTracker/IssueTracker/Controller/MilestoneViewController.swift
  IOS/IssueTracker/IssueTracker/Extensions/Date+Extention.swift
  IOS/IssueTracker/IssueTracker/Model/Issue.swift
  IOS/IssueTracker/IssueTracker/Model/Label.swift
  IOS/IssueTracker/IssueTracker/Model/Milestone.swift
  IOS/IssueTracker/IssueTracker/Model/ResultResponse.swift
  IOS/IssueTracker/IssueTracker/Model/User.swift
  IOS/IssueTracker/IssueTracker/Repository/IssueRepository.swift
  IOS/IssueTracker/IssueTracker/Repository/LabelRepository.swift
  IOS/IssueTracker/IssueTracker/Repository/MilestoneRepository.swift
Labels: 🌝Week 3, 🍎IOS, 🧨FEAT

#68 Feature/iOS/UXkeyboard 사용자 관점에서 키보드 설정
  IOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IOS/IssueTracker/IssueTracker/Controller/IssueDetailViewController.swift
  IOS/IssueTracker/IssueTracker/Controller/LabelDetailViewController.swift
  IOS/IssueTracker/IssueTracker/Controller/MilestoneDetailViewController.swift
  IOS/IssueTracker/IssueTracker/Repository/IssueRepository.swift
Labels: 🌝Week 3, 🍎IOS, 🧨FEAT

#70 Feature/web/공유 스타일 및 컴포넌트 추가, 충돌 해결
  Front-End/package-lock.json
  Front-End/package.json
  Front-End/src/components/common/LabelMilestoneBtn/LabelMilestoneButton.js
  Front-End/src/components/common/index.js
  Front-End/src/components/index.js
  Front-End/src/components/labelComponent/LabelComponent.js
  Front-End/src/components/labelComponent/LabelMilestoneNewButton/topLink.js
  Front-End/src/components/labelComponent/topLink.js
  Front-End/src/pages/labelPage.js
  Front-End/src/style/Buttons/Button.js
  Front-End/src/style/Label/Label.js
  Front-End/src/style/Layout/Layout.js
  Front-End/src/style/index.js
  Front-End/webpack.config.js
Labels: 🌝Week 3, 🦉FE, 🧨FEAT

#80 Feature/web/Label Page API 적용 및 Label Page Error 해결
  .gitignore
  Front-End/src/api/labelTranscation.js
  Front-End/src/components/index.js
  Front-End/src/components/labelComponent/LabelComponent.js
  Front-End/src/components/labelComponent/LabelList/LabelBox/LabelBox.js
  Front-End/src/components/labelComponent/LabelList/LabelBox/LabelEditForm/LabelEditForm.js
  Front-End/src/components/labelComponent/LabelList/LabelBox/LabelViewBox/LabelEditDeleteButtons/LabelEditDeleteButtons.js
  Front-End/webpack.config.js
Labels: 🦉FE, 🧨FEAT

#88 Feature/web/milestone list page 추가구현, css 개선 등
  Back-End/controller/milestone/index.js
  Back-End/routes/milestone/index.js
  Front-End/src/api/milestoneTransaction.js
  Front-End/src/components/MileStoneListComponent/ProgressBar.js
  Front-End/src/components/MileStoneListComponent/index.js
  Front-End/src/components/MileStoneListComponent/mileStoneList.js
  Front-End/src/components/MileStoneListComponent/mileStoneRow.js
  Front-End/src/components/MileStoneListComponent/svg/ClosedIssueSVG.js
  Front-End/src/components/MileStoneListComponent/svg/DueSVG.js
  Front-End/src/components/MileStoneListComponent/svg/OpenIssueSVG.js
  Front-End/src/components/MileStoneListComponent/svg/PastSVG.js
  Front-End/src/components/MileStoneListComponent/topLink.js
Labels: 🌝Week 3, 🐧BE, 👾BUG, 🦉FE, 🧨FEAT

#94 Feature/web/issue filter 구현 및 충돌문제 해결
  Front-End/src/api/commentTransaction.js
  Front-End/src/api/fileTransaction.js
  Front-End/src/api/issueTransaction.js
  Front-End/src/api/labelTransaction.js
  Front-End/src/api/milestoneTransaction.js
  Front-End/src/api/userTransaction.js
  Front-End/src/app.js
  Front-End/src/components/Header/Header.js
  Front-End/src/components/IssueList/FilterBar.js
  Front-End/src/components/IssueList/FilterCancelButton/FilterCancelButton.js
  Front-End/src/components/IssueList/FilterSelectArea/FilterSelect/FilterSelect.js
  Front-End/src/components/IssueList/FilterSelectArea/FilterSelectArea.js
  Front-End/src/components/IssueList/index.js
  Front-End/src/components/common/LabelMilestoneBtn/LabelMilestoneButton.js
  Front-End/src/components/common/SVG/SVG.js
  Front-End/src/components/common/index.js
  Front-End/src/components/labelComponent/LabelComponent.js
  Front-End/src/components/labelComponent/LabelList/LabelBox/LabelBox.js
  Front-End/src/components/labelComponent/LabelMilestoneNewButton/LabelMilestoneNewButton.js
  Front-End/src/components/newIssue/AssigneePopUpRow.js
  Front-End/src/components/newIssue/LabelPopUpRow.js
  Front-End/src/components/newIssue/MilestonePopUpRow.js
  Front-End/src/components/newIssue/NewIssueComponent.js
  Front-End/src/components/newIssue/SelectBox.js
  Front-End/src/pages/EditMileStonePage.js
  Front-End/src/pages/IssueDetailPage.js
  Front-End/src/pages/IssueListPage.js
  Front-End/src/pages/MileStoneListPage.js
  Front-End/src/pages/NewIssuePage.js
  Front-End/src/pages/index.js
  Front-End/src/pages/labelPage.js
  Front-End/src/reducer/filterReducer.js
  Front-End/src/reducer/index.js
  Front-End/src/reducer/issueReducer.js
  Front-End/src/style/Buttons/Button.js
  Front-End/src/style/Layout/Layout.js
  Front-End/src/style/common/common.js
  Front-End/webpack.config.js
Labels: 🦉FE, 🧨FEAT

#95 Feature/web/issue component 추가 적용 및 충돌 해결
  Front-End/src/components/IssueList/FilterSelectArea/FilterSelect/FilterSelect.js
  Front-End/src/components/IssueList/index.js
  Front-End/src/components/newIssue/AssigneePopUpRow.js
  Front-End/src/components/newIssue/LabelPopUpRow.js
  Front-End/src/components/newIssue/MilestonePopUpRow.js
Labels: 👾BUG, 🦉FE

#96 Feature/web/issue back end 에러 해결 및 문제점 해결
  Back-End/controller/comment/index.js
  Back-End/controller/issue/index.js
  Back-End/controller/label/index.js
  Back-End/models/issue.js
  Back-End/routes/comment/index.js
  Back-End/routes/label/index.js
Labels: 🐧BE, 🧨FEAT

#99 Feature/web/Filter Button 구현
  Front-End/src/components/IssueList/FilterBar.js
  Front-End/src/components/IssueList/index.js
  Front-End/src/reducer/filterReducer.js
Labels: 🦉FE, 🧨FEAT

#102 Feature/web/issuelist 체크박스 관련,Mark as open/close 팝업창 구현, bulkupdate 구현
  Back-End/controller/issue/index.js
  Back-End/routes/issue/index.js
  Front-End/src/api/issueTransaction.js
  Front-End/src/components/IssueList/MarkAsArea/MarkAsPopUp.js
  Front-End/src/components/IssueList/index.js
  Front-End/src/components/IssueList/issueList.js
  Front-End/src/components/IssueList/issueRow.js
Labels: 🌝Week 3, 🐧BE, 🦉FE, 🧨FEAT

#103 Feature/web/filter Enter Event
  Back-End/controller/issue/index.js
  Front-End/src/components/IssueList/FilterBar.js
Labels: 🐧BE, 🦉FE, 🧨FEAT

#104 Feature/web/Bug Fix
  Front-End/src/components/IssueList/index.js
Labels: 👾BUG
